### ISSUE TITLE
The link to zeth is not workking  

### ISSUE THREAD

**Issue by Azizadx** [zig-ethereum/.github#1]
I dont know if it is intention or you forget to make the repo public but yeah zeth is not working 

<img width="1278" alt="Screenshot 2023-05-30 at 2 20 26 PM" src="https://github.com/zig-ethereum/.github/assets/45791956/d1590964-d763-4b88-8947-fcb27e357138">

**Comment by bhgomes** [comment]
Yeah, sorry, it's currently private until I've spent a bit more time working on it. I made a note in the `README.md` to clarify.

**Comment by Azizadx** [comment]
alright sure np
